version: '3.8'

services:
  app: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - PYTHONUNBUFFERED=1
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=transaction_prototype
    command: python app.py
    depends_on:
      - db
    networks:
      - flask-network

  db: 
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transaction_prototype
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - flask-network

volumes:
  mysql_data:
networks: 
  flask-network:
  